public class LoggingMediumLevel {
    public static void createAccount(String accName){
        try{
            system.debug('account creation started');
            if(string.isBlank(accName))
            {
                throw new MyException('account name is mandatory');
            }
            account acc= new account(Name=accName);
            insert acc;
            system.debug('the account record got created successfully'+acc.id);
            
        }
        catch(exception e)
        {
            system.debug(LoggingLevel.Error,'there is an error'+e.getMessage());
        }
        finally
        {
            system.debug('the account creation ended');
        }
    }
}